name: Release

on:
  push:
    tags:
      - '*'

jobs:

  build-n-publish:
    name: Build and publish Python 🐍 distributions to PyPI 📦
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install requirements
        run: python -m pip install --user build
      - name: Build release
        run: python -m build --sdist --outdir dist/ .
      - name: Publish distribution 📦 to PyPI (prod)
        uses: pypa/gh-action-pypi-publish@release/v1
